version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopdb
      MYSQL_USER: shopuser
      MYSQL_PASSWORD: shoppass
    volumes:
      - db_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    ports:
      - "3306:3306"
    networks:
      - shopnet

  app:
    image: jonaykb/shop-app:2.31
    container_name: shop-app
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/shopdb
      SPRING_DATASOURCE_USERNAME: shopuser
      SPRING_DATASOURCE_PASSWORD: shoppass
      SENDGRID_API_KEY: YOUR_SECRET_KEY
    ports:
      - "8080:8080"
    networks:
      - shopnet
    volumes:
      - ./uploads:/uploads

  web:
    image: jonaykb/shop-web:2.31
    container_name: shop-web
    restart: always
    environment:
      HOST: kioscobotanico.es
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    networks:
      - shopnet
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro

networks:
  shopnet:

volumes:
  db_data:
