name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image Web
      run: docker build ./localshopsystemv2 --file Dockerfile --tag jonaykb/shop-web:$(date +%s)
    - uses: actions/checkout@v4
    - name: Build the Docker image Api
      run: docker build ./shopsystem --file Dockerfile --tag jonaykb/shop-app:$(date +%s)
    
